version: "3"
services:
  app:
    build: recosideapp/
    container_name: recosideapp
    tty: true
    ports:
      - "49160:8080"
    #volumes:
      #- ./recosideapp:/app
    working_dir: /app
    networks:
      - backend
    depends_on:
      - mysql

  userapp: 
    build: usersideapp/
    container_name: usersideapp
    tty: true
    ports:
      - "49170:8090"
    #volumes:
      #- ./usersideapp:/app
    working_dir: /app
    networks:
      - backend
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
      - BIND-ADDRESS=0.0.0.0
    ports:
      - '3306:3306'
    container_name: mysql
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqls:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=mysql
    - PMA_USER=root
    - PMA_PASSWORD=pass
    ports:
    - 8070:80
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:

volumes:
  mysqls: